// HomeDashboard Weather Event Schema.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: billingreport.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BillingReport contains AWS costs extracted from billing reports.
type BillingReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BillingPeriod this report belongs to.
	BillingPeriod string `protobuf:"bytes,1,opt,name=BillingPeriod,proto3" json:"BillingPeriod,omitempty"`
	// BillingAmount contains a list of amounts realated to a currency.
	BillingAmount map[string]float64 `protobuf:"bytes,2,rep,name=BillingAmount,proto3" json:"BillingAmount,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// TaxAmount contains a list of tax amounts realated to a currency.
	TaxAmount     map[string]float64 `protobuf:"bytes,3,rep,name=TaxAmount,proto3" json:"TaxAmount,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingReport) Reset() {
	*x = BillingReport{}
	mi := &file_billingreport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingReport) ProtoMessage() {}

func (x *BillingReport) ProtoReflect() protoreflect.Message {
	mi := &file_billingreport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingReport.ProtoReflect.Descriptor instead.
func (*BillingReport) Descriptor() ([]byte, []int) {
	return file_billingreport_proto_rawDescGZIP(), []int{0}
}

func (x *BillingReport) GetBillingPeriod() string {
	if x != nil {
		return x.BillingPeriod
	}
	return ""
}

func (x *BillingReport) GetBillingAmount() map[string]float64 {
	if x != nil {
		return x.BillingAmount
	}
	return nil
}

func (x *BillingReport) GetTaxAmount() map[string]float64 {
	if x != nil {
		return x.TaxAmount
	}
	return nil
}

var File_billingreport_proto protoreflect.FileDescriptor

const file_billingreport_proto_rawDesc = "" +
	"\n" +
	"\x13billingreport.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x02\n" +
	"\rBillingReport\x12$\n" +
	"\rBillingPeriod\x18\x01 \x01(\tR\rBillingPeriod\x12N\n" +
	"\rBillingAmount\x18\x02 \x03(\v2(.events.BillingReport.BillingAmountEntryR\rBillingAmount\x12B\n" +
	"\tTaxAmount\x18\x03 \x03(\v2$.events.BillingReport.TaxAmountEntryR\tTaxAmount\x1a@\n" +
	"\x12BillingAmountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a<\n" +
	"\x0eTaxAmountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B\n" +
	"Z\b.;eventsb\x06proto3"

var (
	file_billingreport_proto_rawDescOnce sync.Once
	file_billingreport_proto_rawDescData []byte
)

func file_billingreport_proto_rawDescGZIP() []byte {
	file_billingreport_proto_rawDescOnce.Do(func() {
		file_billingreport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billingreport_proto_rawDesc), len(file_billingreport_proto_rawDesc)))
	})
	return file_billingreport_proto_rawDescData
}

var file_billingreport_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_billingreport_proto_goTypes = []any{
	(*BillingReport)(nil), // 0: events.BillingReport
	nil,                   // 1: events.BillingReport.BillingAmountEntry
	nil,                   // 2: events.BillingReport.TaxAmountEntry
}
var file_billingreport_proto_depIdxs = []int32{
	1, // 0: events.BillingReport.BillingAmount:type_name -> events.BillingReport.BillingAmountEntry
	2, // 1: events.BillingReport.TaxAmount:type_name -> events.BillingReport.TaxAmountEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_billingreport_proto_init() }
func file_billingreport_proto_init() {
	if File_billingreport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billingreport_proto_rawDesc), len(file_billingreport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_billingreport_proto_goTypes,
		DependencyIndexes: file_billingreport_proto_depIdxs,
		MessageInfos:      file_billingreport_proto_msgTypes,
	}.Build()
	File_billingreport_proto = out.File
	file_billingreport_proto_goTypes = nil
	file_billingreport_proto_depIdxs = nil
}
